//! Constants used by the ERC20 contract.

/// Name of named-key for `name`.
pub const NAME_KEY_NAME: &str = "name";
/// Name of named-key for `symbol`
pub const SYMBOL_KEY_NAME: &str = "symbol";
/// Name of named-key for `granularity`
pub const GRANULARITY_KEY_NAME: &str = "granularity";
/// Name of named-key for `decimals`
pub const DECIMALS_KEY_NAME: &str = "decimals";
/// Name of named-key for `contract`
pub const ERC777_TOKEN_CONTRACT_KEY_NAME: &str = "erc777_token_contract";
/// Name of dictionary-key for `balances`
pub const BALANCES_KEY_NAME: &str = "balances";
/// Name of named-key for `total_supply`
pub const TOTAL_SUPPLY_KEY_NAME: &str = "total_supply";
/// Name of named-key for `default_operators`
pub const DEFAULT_OPERATORS_KEY_NAME: &str = "default_operators";

/// Name of `name` entry point.
pub const NAME_ENTRY_POINT_NAME: &str = "name";
/// Name of `symbol` entry point.
pub const SYMBOL_ENTRY_POINT_NAME: &str = "symbol";
/// Name of `granularity` entry point.
pub const GRANULARITY_ENTRY_POINT_NAME: &str = "granularity";
/// Name of `decimals` entry point.
pub const DECIMALS_ENTRY_POINT_NAME: &str = "decimals";
/// Name of `balance_of` entry point.
pub const BALANCE_OF_ENTRY_POINT_NAME: &str = "balance_of";
/// Name of `transfer` entry point.
pub const TRANSFER_ENTRY_POINT_NAME: &str = "transfer";
/// Name of `transfer_from` entry point.
pub const TRANSFER_FROM_ENTRY_POINT_NAME: &str = "transfer_from";
/// Name of `total_supply` entry point.
pub const TOTAL_SUPPLY_ENTRY_POINT_NAME: &str = "total_supply";
/// Name of `send` entry point.
pub const SEND_ENTRY_POINT_NAME: &str = "send";
/// Name of `burn` entry point.
pub const BURN_ENTRY_POINT_NAME: &str = "burn";
/// Name of `is_operator_for` entry point.
pub const IS_OPERATOR_FOR_ENTRY_POINT_NAME: &str = "is_operator_for";
/// Name of `authorize_operator` entry point.
pub const AUTHORIZE_OPERATOR_ENTRY_POINT_NAME: &str = "authorize_operator";
/// Name of `revoke_operator` entry point.
pub const REVOKE_OPERATOR_ENTRY_POINT_NAME: &str = "revoke_operator";
/// Name of `default_operators` entry point.
pub const DEFAULT_OPERATORS_ENTRY_POINT_NAME: &str = "default_operators";
/// Name of `operator_send` entry point.
pub const OPERATOR_SEND_ENTRY_POINT_NAME: &str = "operator_send";
/// Name of `operator_burn` entry point.
pub const OPERATOR_BURN_ENTRY_POINT_NAME: &str = "operator_burn";

/// Name of `address` runtime argument.
pub const ADDRESS_RUNTIME_ARG_NAME: &str = "address";
/// Name of `owner` runtime argument.
pub const OWNER_RUNTIME_ARG_NAME: &str = "owner";
/// Name of `spender` runtime argument.
pub const SPENDER_RUNTIME_ARG_NAME: &str = "spender";
/// Name of `amount` runtime argument.
pub const AMOUNT_RUNTIME_ARG_NAME: &str = "amount";
/// Name of `recipient` runtime argument.
pub const RECIPIENT_RUNTIME_ARG_NAME: &str = "recipient";
/// Name of `name` runtime argument.
pub const NAME_RUNTIME_ARG_NAME: &str = "name";
/// Name of `symbol` runtime argument.
pub const SYMBOL_RUNTIME_ARG_NAME: &str = "symbol";
/// Name of `decimals` runtime argument.
pub const DECIMALS_RUNTIME_ARG_NAME: &str = "decimals";
/// Name of `granularity` runtime argument.
pub const GRANULARITY_RUNTIME_ARG_NAME: &str = "granularity";
/// Name of `total_supply` runtime argument.
pub const TOTAL_SUPPLY_RUNTIME_ARG_NAME: &str = "total_supply";
/// Name of `operator` runtime argument.
pub const OPERATOR_RUNTIME_ARG_NAME: &str = "operator";
/// Name of `token_holder` runtime argument.
pub const TOKEN_HOLDER_RUNTIME_ARG_NAME: &str = "token_holder";